<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JadwalDokterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('jadwal_dokters')->insert([
            [
                'id_dokter' => 1,
                'hari' => 'Senin',
                'jam_mulai' => '16:00:00',
                'jam_selesai' => '19:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 1,
                'hari' => 'Rabu',
                'jam_mulai' => '16:00:00',
                'jam_selesai' => '19:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 1,
                'hari' => 'Kamis',
                'jam_mulai' => '16:00:00',
                'jam_selesai' => '19:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 2,
                'hari' => 'Selasa',
                'jam_mulai' => '16:00:00',
                'jam_selesai' => '18:00:00',
                'kuota' => 3,
            ],
            [
                'id_dokter' => 3,
                'hari' => 'Senin',
                'jam_mulai' => '16:00:00',
                'jam_selesai' => '18:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 3,
                'hari' => 'Kamis',
                'jam_mulai' => '16:00:00',
                'jam_selesai' => '18:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 4,
                'hari' => 'Senin',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 4,
                'hari' => 'Selasa',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 4,
                'hari' => 'Rabu',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 4,
                'hari' => 'Kamis',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 4,
                'hari' => 'Jumat',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 4,
                'hari' => 'Sabtu',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 5,
                'hari' => 'Selasa',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:00:00',
                'kuota' => 3,
            ],
            [
                'id_dokter' => 5,
                'hari' => 'Kamis',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:00:00',
                'kuota' => 3,
            ],
            [
                'id_dokter' => 5,
                'hari' => 'Jumat',
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '15:00:00',
                'kuota' => 3,
            ],
            [
                'id_dokter' => 6,
                'hari' => 'Senin',
                'jam_mulai' => '08:30:00',
                'jam_selesai' => '12:30:00',
                'kuota' => 8,
            ],
            [
                'id_dokter' => 6,
                'hari' => 'Selasa',
                'jam_mulai' => '08:30:00',
                'jam_selesai' => '12:30:00',
                'kuota' => 8,
            ],
            [
                'id_dokter' => 6,
                'hari' => 'Rabu',
                'jam_mulai' => '08:30:00',
                'jam_selesai' => '12:30:00',
                'kuota' => 8,
            ],
            [
                'id_dokter' => 6,
                'hari' => 'Kamis',
                'jam_mulai' => '08:30:00',
                'jam_selesai' => '12:30:00',
                'kuota' => 8,
            ],
            [
                'id_dokter' => 6,
                'hari' => 'Jumat',
                'jam_mulai' => '08:30:00',
                'jam_selesai' => '12:30:00',
                'kuota' => 8,
            ],
            [
                'id_dokter' => 6,
                'hari' => 'Sabtu',
                'jam_mulai' => '08:30:00',
                'jam_selesai' => '12:30:00',
                'kuota' => 8,
            ],
            [
                'id_dokter' => 6,
                'hari' => 'Senin',
                'jam_mulai' => '17:30:00',
                'jam_selesai' => '19:00:00',
                'kuota' => 2,
            ],
            [
                'id_dokter' => 6,
                'hari' => 'Selasa',
                'jam_mulai' => '17:30:00',
                'jam_selesai' => '19:00:00',
                'kuota' => 2,
            ],
            [
                'id_dokter' => 6,
                'hari' => 'Rabu',
                'jam_mulai' => '17:30:00',
                'jam_selesai' => '19:00:00',
                'kuota' => 2,
            ],
            [
                'id_dokter' => 6,
                'hari' => 'Kamis',
                'jam_mulai' => '17:30:00',
                'jam_selesai' => '19:00:00',
                'kuota' => 2,
            ],
            [
                'id_dokter' => 6,
                'hari' => 'Jumat',
                'jam_mulai' => '17:30:00',
                'jam_selesai' => '19:00:00',
                'kuota' => 2,
            ],
            [
                'id_dokter' => 7,
                'hari' => 'Senin',
                'jam_mulai' => '14:30:00',
                'jam_selesai' => '19:30:00',
                'kuota' => 12,
            ],
            [
                'id_dokter' => 7,
                'hari' => 'Rabu',
                'jam_mulai' => '14:30:00',
                'jam_selesai' => '19:30:00',
                'kuota' => 12,
            ],
            [
                'id_dokter' => 8,
                'hari' => 'Senin',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '10:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 8,
                'hari' => 'Kamis',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '10:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 8,
                'hari' => 'Jumat',
                'jam_mulai' => '15:00:00',
                'jam_selesai' => '17:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 9,
                'hari' => 'Senin',
                'jam_mulai' => '09:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 9,
                'hari' => 'Selasa',
                'jam_mulai' => '09:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 9,
                'hari' => 'Rabu',
                'jam_mulai' => '09:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 9,
                'hari' => 'Kamis',
                'jam_mulai' => '09:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 9,
                'hari' => 'Jumat',
                'jam_mulai' => '09:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 9,
                'hari' => 'Sabtu',
                'jam_mulai' => '09:00:00',
                'jam_selesai' => '14:00:00',
                'kuota' => 12,
            ],
            [
                'id_dokter' => 10,
                'hari' => 'Senin',
                'jam_mulai' => '18:00:00',
                'jam_selesai' => '22:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 10,
                'hari' => 'Selasa',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '14:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 10,
                'hari' => 'Selasa',
                'jam_mulai' => '16:00:00',
                'jam_selesai' => '22:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 10,
                'hari' => 'Kamis',
                'jam_mulai' => '16:00:00',
                'jam_selesai' => '22:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 10,
                'hari' => 'Sabtu',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 8,
            ],
            [
                'id_dokter' => 11,
                'hari' => 'Senin',
                'jam_mulai' => '18:00:00',
                'jam_selesai' => '20:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 11,
                'hari' => 'Selasa',
                'jam_mulai' => '18:00:00',
                'jam_selesai' => '20:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 11,
                'hari' => 'Rabu',
                'jam_mulai' => '18:00:00',
                'jam_selesai' => '20:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 11,
                'hari' => 'Kamis',
                'jam_mulai' => '18:00:00',
                'jam_selesai' => '20:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 11,
                'hari' => 'Jumat',
                'jam_mulai' => '16:00:00',
                'jam_selesai' => '18:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 11,
                'hari' => 'Sabtu',
                'jam_mulai' => '14:00:00',
                'jam_selesai' => '16:30:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 12,
                'hari' => 'Senin',
                'jam_mulai' => '07:00:00',
                'jam_selesai' => '09:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 12,
                'hari' => 'Kamis',
                'jam_mulai' => '07:00:00',
                'jam_selesai' => '09:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 12,
                'hari' => 'Sabtu',
                'jam_mulai' => '07:00:00',
                'jam_selesai' => '09:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 12,
                'hari' => 'Rabu',
                'jam_mulai' => '19:00:00',
                'jam_selesai' => '21:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 12,
                'hari' => 'Jumat',
                'jam_mulai' => '14:00:00',
                'jam_selesai' => '16:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 13,
                'hari' => 'Senin',
                'jam_mulai' => '14:30:00',
                'jam_selesai' => '16:00:00',
                'kuota' => 3,
            ],
            [
                'id_dokter' => 13,
                'hari' => 'Rabu',
                'jam_mulai' => '14:30:00',
                'jam_selesai' => '16:00:00',
                'kuota' => 3,
            ],
            [
                'id_dokter' => 13,
                'hari' => 'Jumat',
                'jam_mulai' => '12:30:00',
                'jam_selesai' => '14:00:00',
                'kuota' => 3,
            ],
            [
                'id_dokter' => 14,
                'hari' => 'Senin',
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '15:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 14,
                'hari' => 'Kamis',
                'jam_mulai' => '15:00:00',
                'jam_selesai' => '17:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 14,
                'hari' => 'Sabtu',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '11:00:00',
                'kuota' => 8,
            ],
            [
                'id_dokter' => 15,
                'hari' => 'Senin',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 15,
                'hari' => 'Selasa',
                'jam_mulai' => '08:30:00',
                'jam_selesai' => '10:00:00',
                'kuota' => 3,
            ],
            [
                'id_dokter' => 15,
                'hari' => 'Rabu',
                'jam_mulai' => '08:30:00',
                'jam_selesai' => '10:00:00',
                'kuota' => 3,
            ],
            [
                'id_dokter' => 15,
                'hari' => 'Kamis',
                'jam_mulai' => '08:30:00',
                'jam_selesai' => '10:00:00',
                'kuota' => 3,
            ],
            [
                'id_dokter' => 15,
                'hari' => 'Jumat',
                'jam_mulai' => '08:30:00',
                'jam_selesai' => '10:00:00',
                'kuota' => 3,
            ],
            [
                'id_dokter' => 15,
                'hari' => 'Sabtu',
                'jam_mulai' => '11:00:00',
                'jam_selesai' => '12:00:00',
                'kuota' => 2,
            ],
            [
                'id_dokter' => 16,
                'hari' => 'Sabtu',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 16,
                'hari' => 'Senin',
                'jam_mulai' => '14:00:00',
                'jam_selesai' => '16:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 16,
                'hari' => 'Rabu',
                'jam_mulai' => '14:00:00',
                'jam_selesai' => '16:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 16,
                'hari' => 'Jumat',
                'jam_mulai' => '14:00:00',
                'jam_selesai' => '16:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 16,
                'hari' => 'Selasa',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 16,
                'hari' => 'Kamis',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:00:00',
                'kuota' => 5,
            ],
            [
                'id_dokter' => 17,
                'hari' => 'Senin',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 8,
            ],
            [
                'id_dokter' => 17,
                'hari' => 'Selasa',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 8,
            ],
            [
                'id_dokter' => 17,
                'hari' => 'Rabu',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 8,
            ],
            [
                'id_dokter' => 17,
                'hari' => 'Kamis',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 8,
            ],
            [
                'id_dokter' => 17,
                'hari' => 'Sabtu',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '13:00:00',
                'kuota' => 8,
            ],
            [
                'id_dokter' => 17,
                'hari' => 'Jumat',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '11:00:00',
                'kuota' => 3,
            ],
            [
                'id_dokter' => 18,
                'hari' => 'Senin',
                'jam_mulai' => '16:30:00',
                'jam_selesai' => '18:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 18,
                'hari' => 'Selasa',
                'jam_mulai' => '16:30:00',
                'jam_selesai' => '18:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 18,
                'hari' => 'Rabu',
                'jam_mulai' => '16:30:00',
                'jam_selesai' => '18:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 18,
                'hari' => 'Kamis',
                'jam_mulai' => '16:30:00',
                'jam_selesai' => '18:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 18,
                'hari' => 'Jumat',
                'jam_mulai' => '11:30:00',
                'jam_selesai' => '12:30:00',
                'kuota' => 3,
            ],
            [
                'id_dokter' => 18,
                'hari' => 'Jumat',
                'jam_mulai' => '17:00:00',
                'jam_selesai' => '17:45:00',
                'kuota' => 2,
            ],
            [
                'id_dokter' => 19,
                'hari' => 'Rabu',
                'jam_mulai' => '14:30:00',
                'jam_selesai' => '16:00:00',
                'kuota' => 4,
            ],
            [
                'id_dokter' => 19,
                'hari' => 'Jumat',
                'jam_mulai' => '14:30:00',
                'jam_selesai' => '17:00:00',
                'kuota' => 6,
            ],
            [
                'id_dokter' => 20,
                'hari' => 'Senin',
                'jam_mulai' => '19:00:00',
                'jam_selesai' => '21:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 20,
                'hari' => 'Selasa',
                'jam_mulai' => '19:00:00',
                'jam_selesai' => '21:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 20,
                'hari' => 'Rabu',
                'jam_mulai' => '19:00:00',
                'jam_selesai' => '21:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 20,
                'hari' => 'Kamis',
                'jam_mulai' => '19:00:00',
                'jam_selesai' => '21:00:00',
                'kuota' => 10,
            ],
            [
                'id_dokter' => 20,
                'hari' => 'Jumat',
                'jam_mulai' => '19:00:00',
                'jam_selesai' => '21:00:00',
                'kuota' => 10,
            ],
        ]);
    }
}
